apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: node-app
  name: node-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: miroirs/node_devops:0.0.1
        env:
          - name: NODE_ENV
            value: production
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
